// <auto-generated />
using System;
using LasPollasHermanas.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LasPollasHermanas.Server.ModelsMigrations
{
    [DbContext(typeof(DildoStoreContext))]
    partial class DildoStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.Dildo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MortalUserId")
                        .HasColumnType("int");

                    b.Property<int?>("MortalUserId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MortalUserId");

                    b.HasIndex("MortalUserId1");

                    b.ToTable("Dildos");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.MortalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("MortalUsers");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.AdminUser", b =>
                {
                    b.HasOne("LasPollasHermanas.Shared.Models.Account", "Account")
                        .WithOne("AdminUser")
                        .HasForeignKey("LasPollasHermanas.Shared.Models.AdminUser", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.Dildo", b =>
                {
                    b.HasOne("LasPollasHermanas.Shared.Models.MortalUser", null)
                        .WithMany("BoughtDildos")
                        .HasForeignKey("MortalUserId");

                    b.HasOne("LasPollasHermanas.Shared.Models.MortalUser", null)
                        .WithMany("CurrentDildos")
                        .HasForeignKey("MortalUserId1");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.MortalUser", b =>
                {
                    b.HasOne("LasPollasHermanas.Shared.Models.Account", "Account")
                        .WithOne("MortalUser")
                        .HasForeignKey("LasPollasHermanas.Shared.Models.MortalUser", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.Account", b =>
                {
                    b.Navigation("AdminUser");

                    b.Navigation("MortalUser");
                });

            modelBuilder.Entity("LasPollasHermanas.Shared.Models.MortalUser", b =>
                {
                    b.Navigation("BoughtDildos");

                    b.Navigation("CurrentDildos");
                });
#pragma warning restore 612, 618
        }
    }
}
